### ISSUE TITLE
BACKEND and CDN urls (question)

### ISSUE THREAD

**Issue by jhmcstanton** [elba/website#9]
In the docker compose file I see that `BACKEND_URL` and `CDN_URL` are at [chaos.tk domains](https://github.com/elba/website/blob/master/docker-compose.yml#L50-L51). 

Are those setup? They didn't seem available when I took a look the other day

**Comment by andylokandy** [comment]
It's my testing domain. You should always modify it to your own domain, or use the default in .env for local testing.
